{% set name = "dbt-dremio" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt-dremio-{{ version }}.tar.gz
  sha256: 5bf68c20efe4cd331fd274dcaa371463b792e123e5ca21545fe2150b700d5b51

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dbt-core >=1.2,<1.6.0

test:
  imports:
    - dbt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dremio/dbt-dremio
  summary: The Dremio adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
