{% set name = "dbt-dremio" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt-dremio-{{ version }}.tar.gz
  sha256: e3168ab1508282e1f511cb103cd68c2c0d84e53f9e77d96495b2e961355fc4fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - dbt-core>=1.2,<=1.4.5

test:
  imports:
    - dbt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dremio/dbt-dremio
  summary: The Dremio adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
