{% set name = "dbt-dremio" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt-dremio-{{ version }}.tar.gz
  sha256: f9e5baf01b6256c7c1dc0456bfa0d7444628359f91136a90214c7c63db8f5181

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - dbt-core >=1.2,<=1.3.2

test:
  imports:
    - dbt

about:
  home: https://github.com/dremio/dbt-dremio
  summary: The Dremio adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jlarue26
    - rxm7706
